# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default=0, upload_to='artist_img'),
            preserve_default=False,
        ),
    ]
